In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_json('/content/sample_data/anscombe.json')
df.head()

  Series   X     Y
0      I  10  8.04
1      I   8  6.95
2      I  13  7.58
3      I   9  8.81
4      I  11  8.33

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Series  44 non-null     object
 1   X       44 non-null     int64
 2   Y       44 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.2+ KB

In [9]:
df.dropna(how='any',inplace=True)
df.head()

  Series   X     Y
0      I  10  8.04
1      I   8  6.95
2      I  13  7.58
3      I   9  8.81
4      I  11  8.33

In [10]:
df["X"].value_counts()//len(df)*100

X
8     0
10    0
13    0
9     0
11    0
14    0
6     0
4     0
12    0
7     0
5     0
19    0
Name: count, dtype: int64

In [11]:
x=df.drop(['X','Y'],axis=1)
x.head()

  Series
0      I
1      I
2      I
3      I
4      I

In [12]:
y=df.X.values
y

array([10,  8, 13,  9, 11, 14,  6,  4, 12,  7,  5, 10,  8, 13,  9, 11, 14,
        6,  4, 12,  7,  5, 10,  8, 13,  9, 11, 14,  6,  4, 12,  7,  5,  8,
        8,  8,  8,  8,  8,  8, 19,  8,  8,  8])

In [13]:

x.columns

Index(['Series'], dtype='object')

In [14]:
x=df.drop(['X','Y'],axis=1)
x=pd.get_dummies(x,columns=['Series'],drop_first=True)
x.head()

   Series_II  Series_III  Series_IV
0      False       False      False
1      False       False      False
2      False       False      False
3      False       False      False
4      False       False      False

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
len(x_train),len(x_test),len(y_train),len(y_test)

(35, 9, 35, 9)

***feature sealing***

In [17]:
from sklearn.preprocessing import StandardScaler as standardScaler
sc=standardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [18]:
x_train

array([[-0.63245553,  2.        , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [ 1.58113883, -0.5       , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553, -0.5       , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553,  2.        , -0.58834841],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [ 1.58113883, -0.5       , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553, -0.5       , -0.58834841]])

In [19]:
!pip install matplotlib-venn

Requirement already satisfied: matplotlib-venn in /usr/local/lib/python3.12/dist-packages (1.1.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from matplotlib-venn) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from matplotlib-venn) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from matplotlib-venn) (1.16.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->matplotlib-venn) (1.17.0)

In [39]:
!apt-get -qq install -y libfluidsynth1

E: Package 'libfluidsynth1' has no installation candidate

In [40]:
# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

Selecting previously unselected package libarchive-dev:amd64.
(Reading database ... 118243 files and directories currently installed.)
Preparing to unpack .../libarchive-dev_3.6.0-1ubuntu1.7_amd64.deb ...
Unpacking libarchive-dev:amd64 (3.6.0-1ubuntu1.7) ...
Setting up libarchive-dev:amd64 (3.6.0-1ubuntu1.7) ...
Processing triggers for man-db (2.10.2-1) ...
Collecting libarchive
  Downloading libarchive-0.4.7.tar.gz (23 kB)
  Preparing metadata (setup.py) ... done
Collecting nose (from libarchive)
  Downloading nose-1.3.7-py3-none-any.whl.metadata (1.7 kB)
Downloading nose-1.3.7-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 6.6 MB/s eta 0:00:00
Building wheels for collected packages: libarchive
  Building wheel for libarchive (setup.py) ... done
  Created wheel for libarchive: filename=libarchive-0.4.7-py3-none-any.whl size=31629 sha256=2db5a52e26490050940d6b94b8df186afa3a001daacefb80b8b663a5534ea121
  Stored in directory: /root/.cache/pip/wheels/29/20/ab/f101da7b245b996aa097685ef742243725ea6150f5b3b6d9ed
Successfully built libarchive
Installing collected packages: nose, libarchive
Successfully installed libarchive-0.4.7 nose-1.3.7

In [41]:
# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

Requirement already satisfied: pydot in /usr/local/lib/python3.12/dist-packages (4.0.1)
Requirement already satisfied: pyparsing>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from pydot) (3.3.2)

In [42]:
!pip install cartopy
import cartopy

Collecting cartopy
  Downloading cartopy-0.25.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from cartopy) (2.0.2)
Requirement already satisfied: matplotlib>=3.6 in /usr/local/lib/python3.12/dist-packages (from cartopy) (3.10.0)
Requirement already satisfied: shapely>=2.0 in /usr/local/lib/python3.12/dist-packages (from cartopy) (2.1.2)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.12/dist-packages (from cartopy) (26.2)
Requirement already satisfied: pyshp>=2.3 in /usr/local/lib/python3.12/dist-packages (from cartopy) (3.1.1)
Requirement already satisfied: pyproj>=3.3.1 in /usr/local/lib/python3.12/dist-packages (from cartopy) (3.7.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (2.9.0.post0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyproj>=3.3.1->cartopy) (2026.6.17)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.6->cartopy) (1.17.0)
Downloading cartopy-0.25.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 60.3 MB/s eta 0:00:00
Installing collected packages: cartopy
Successfully installed cartopy-0.25.0

In [43]:
from sklearn.neighbors import KNeighborsClassifier

In [44]:
model=KNeighborsClassifier()

In [45]:
model.fit(x_train,y_train)

KNeighborsClassifier()

In [46]:
y_pred=model.predict(x_test)
y_pred

array([4, 8, 4, 4, 4, 4, 4, 4, 8])

In [47]:
y_test

array([12,  8, 14, 11,  5,  9,  6, 10,  8])

In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

22.22222222222222

In [49]:
x_test[:]

array([[-0.63245553,  2.        , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317],
       [-0.63245553,  2.        , -0.58834841],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553, -0.5       , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [-0.63245553,  2.        , -0.58834841],
       [ 1.58113883, -0.5       , -0.58834841],
       [-0.63245553, -0.5       ,  1.69967317]])

In [50]:
data=[[0,2,89,178,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0]]

In [51]:
data_sc = sc.transform(data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

ValueError: X has 23 features, but StandardScaler is expecting 3 features as input.

In [52]:
single=model.predict(data_sc)
print(single)

[4]

In [53]:
from sklearn.tree import DecisionTreeClassifier
model1=DecisionTreeClassifier()
model1.fit(x_train,y_train)

DecisionTreeClassifier()

In [54]:
y_pred1=model1.predict(x_test)
print(y_pred1)
print(y_test)

[4 8 4 4 4 4 4 4 8]
[12  8 14 11  5  9  6 10  8]

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)*100

22.22222222222222

In [56]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()
model2.fit(x_train,y_train)

RandomForestClassifier()

In [57]:
y_pred2=model2.predict(x_test)
print(y_pred2)
print(y_test)

[7 8 7 6 6 7 7 7 8]
[12  8 14 11  5  9  6 10  8]

In [58]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)*100

22.22222222222222

In [59]:
def calculat_gini(df_label):
    classes, class_counts = np.unique(df_label, return_counts=True)
    probabilities = class_counts / len(df_label)
    entropy_value = -np.sum(probabilities * np.log2(probabilities))
    print(entropy_value)

In [61]:
calculat_gini(y)

3.285463633240277

In [62]:
def calculate_entropy1(labels):
    _, counts = np.unique(labels, return_counts=True)
    probabilities = counts / counts.sum()

    return -np.sum(probabilities * np.log2(probabilities))

In [63]:
calculate_entropy1(x)

np.float64(0.8112781244591328)

In [64]:
from sklearn.ensemble import AdaBoostClassifier
model3=AdaBoostClassifier(n_estimators=100)
model3.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=100)

In [65]:
y_pred3=model3.predict(x_test)

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred3)*100

22.22222222222222

In [1]:
!pip install catboost
from catboost import CatBoostClassifier

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 7.6 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [30]:
q=CatBoostClassifier()
q.fit(x_train,y_train)

Learning rate set to 0.066692
0:	learn: 2.4519501	total: 46.2ms	remaining: 46.1s
1:	learn: 2.4206527	total: 46.4ms	remaining: 23.1s
2:	learn: 2.3909493	total: 46.5ms	remaining: 15.5s
3:	learn: 2.3635038	total: 46.6ms	remaining: 11.6s
4:	learn: 2.3375375	total: 46.7ms	remaining: 9.3s
5:	learn: 2.3124163	total: 46.9ms	remaining: 7.77s
6:	learn: 2.2894832	total: 47ms	remaining: 6.67s
7:	learn: 2.2721123	total: 47.1ms	remaining: 5.84s
8:	learn: 2.2516412	total: 47.2ms	remaining: 5.2s
9:	learn: 2.2316172	total: 47.3ms	remaining: 4.68s
10:	learn: 2.2151766	total: 47.4ms	remaining: 4.26s
11:	learn: 2.1972335	total: 47.6ms	remaining: 3.92s
12:	learn: 2.1803366	total: 47.8ms	remaining: 3.63s
13:	learn: 2.1644926	total: 47.9ms	remaining: 3.37s
14:	learn: 2.1494847	total: 48ms	remaining: 3.15s
15:	learn: 2.1353283	total: 48.2ms	remaining: 2.96s
16:	learn: 2.1220566	total: 48.3ms	remaining: 2.79s
17:	learn: 2.1100416	total: 48.4ms	remaining: 2.64s
18:	learn: 2.0980910	total: 48.6ms	remaining: 2.51s
19:	learn: 2.0875700	total: 48.7ms	remaining: 2.38s
20:	learn: 2.0784108	total: 48.8ms	remaining: 2.27s
21:	learn: 2.0682774	total: 48.9ms	remaining: 2.17s
22:	learn: 2.0593646	total: 49ms	remaining: 2.08s
23:	learn: 2.0528157	total: 49.1ms	remaining: 2s
24:	learn: 2.0455083	total: 49.2ms	remaining: 1.92s
25:	learn: 2.0386498	total: 49.3ms	remaining: 1.85s
26:	learn: 2.0305757	total: 49.4ms	remaining: 1.78s
27:	learn: 2.0233658	total: 49.6ms	remaining: 1.72s
28:	learn: 2.0160431	total: 49.7ms	remaining: 1.66s
29:	learn: 2.0089037	total: 49.8ms	remaining: 1.61s
30:	learn: 2.0020860	total: 50ms	remaining: 1.56s
31:	learn: 1.9955701	total: 50.1ms	remaining: 1.52s
32:	learn: 1.9893376	total: 50.3ms	remaining: 1.47s
33:	learn: 1.9835254	total: 50.4ms	remaining: 1.43s
34:	learn: 1.9779737	total: 50.5ms	remaining: 1.39s
35:	learn: 1.9724860	total: 50.7ms	remaining: 1.36s
36:	learn: 1.9672209	total: 50.9ms	remaining: 1.32s
37:	learn: 1.9638367	total: 50.9ms	remaining: 1.29s
38:	learn: 1.9589285	total: 51.1ms	remaining: 1.26s
39:	learn: 1.9542097	total: 51.3ms	remaining: 1.23s
40:	learn: 1.9507332	total: 51.4ms	remaining: 1.2s
41:	learn: 1.9479993	total: 51.5ms	remaining: 1.17s
42:	learn: 1.9438540	total: 51.6ms	remaining: 1.15s
43:	learn: 1.9414013	total: 51.7ms	remaining: 1.12s
44:	learn: 1.9391059	total: 51.8ms	remaining: 1.1s
45:	learn: 1.9351514	total: 51.9ms	remaining: 1.08s
46:	learn: 1.9313339	total: 52ms	remaining: 1.05s
47:	learn: 1.9276463	total: 52.2ms	remaining: 1.03s
48:	learn: 1.9240821	total: 52.4ms	remaining: 1.02s
49:	learn: 1.9206353	total: 52.5ms	remaining: 998ms
50:	learn: 1.9182556	total: 52.6ms	remaining: 979ms
51:	learn: 1.9149950	total: 52.8ms	remaining: 963ms
52:	learn: 1.9118369	total: 53ms	remaining: 946ms
53:	learn: 1.9102765	total: 53.1ms	remaining: 930ms
54:	learn: 1.9072702	total: 53.2ms	remaining: 914ms
55:	learn: 1.9052537	total: 53.3ms	remaining: 899ms
56:	learn: 1.9028638	total: 53.5ms	remaining: 884ms
57:	learn: 1.9000799	total: 53.6ms	remaining: 871ms
58:	learn: 1.8973761	total: 53.8ms	remaining: 858ms
59:	learn: 1.8960264	total: 53.9ms	remaining: 844ms
60:	learn: 1.8942841	total: 54ms	remaining: 831ms
61:	learn: 1.8931560	total: 54.1ms	remaining: 818ms
62:	learn: 1.8911050	total: 54.2ms	remaining: 807ms
63:	learn: 1.8891223	total: 54.3ms	remaining: 795ms
64:	learn: 1.8867286	total: 54.5ms	remaining: 784ms
65:	learn: 1.8843975	total: 54.7ms	remaining: 774ms
66:	learn: 1.8821265	total: 54.8ms	remaining: 763ms
67:	learn: 1.8803623	total: 54.9ms	remaining: 753ms
68:	learn: 1.8781955	total: 55.1ms	remaining: 744ms
69:	learn: 1.8773491	total: 55.2ms	remaining: 734ms
70:	learn: 1.8752584	total: 55.4ms	remaining: 724ms
71:	learn: 1.8733071	total: 55.5ms	remaining: 715ms
72:	learn: 1.8713127	total: 55.6ms	remaining: 706ms
73:	learn: 1.8705702	total: 55.7ms	remaining: 697ms
74:	learn: 1.8686409	total: 55.9ms	remaining: 689ms
75:	learn: 1.8667556	total: 56ms	remaining: 681ms
76:	learn: 1.8649128	total: 56.2ms	remaining: 674ms
77:	learn: 1.8631108	total: 56.3ms	remaining: 666ms
78:	learn: 1.8613483	total: 56.5ms	remaining: 659ms
79:	learn: 1.8596238	total: 56.6ms	remaining: 651ms
80:	learn: 1.8580164	total: 56.8ms	remaining: 644ms
81:	learn: 1.8563621	total: 56.9ms	remaining: 637ms
82:	learn: 1.8548278	total: 57.1ms	remaining: 631ms
83:	learn: 1.8536092	total: 57.2ms	remaining: 624ms
84:	learn: 1.8524225	total: 57.4ms	remaining: 617ms
85:	learn: 1.8508832	total: 57.5ms	remaining: 611ms
86:	learn: 1.8493744	total: 57.6ms	remaining: 605ms
87:	learn: 1.8478950	total: 57.8ms	remaining: 599ms
88:	learn: 1.8464441	total: 57.9ms	remaining: 593ms
89:	learn: 1.8450209	total: 58ms	remaining: 587ms
90:	learn: 1.8436246	total: 58.2ms	remaining: 581ms
91:	learn: 1.8426969	total: 58.3ms	remaining: 575ms
92:	learn: 1.8413420	total: 58.4ms	remaining: 570ms
93:	learn: 1.8400119	total: 58.6ms	remaining: 564ms
94:	learn: 1.8387059	total: 58.7ms	remaining: 559ms
95:	learn: 1.8374232	total: 58.8ms	remaining: 554ms
96:	learn: 1.8361633	total: 59ms	remaining: 549ms
97:	learn: 1.8349255	total: 59.1ms	remaining: 544ms
98:	learn: 1.8337091	total: 59.2ms	remaining: 539ms
99:	learn: 1.8325135	total: 59.4ms	remaining: 534ms
100:	learn: 1.8313383	total: 59.5ms	remaining: 530ms
101:	learn: 1.8301827	total: 59.6ms	remaining: 525ms
102:	learn: 1.8290464	total: 59.8ms	remaining: 521ms
103:	learn: 1.8279288	total: 59.9ms	remaining: 516ms
104:	learn: 1.8268295	total: 60.1ms	remaining: 512ms
105:	learn: 1.8257479	total: 60.2ms	remaining: 508ms
106:	learn: 1.8246835	total: 60.3ms	remaining: 504ms
107:	learn: 1.8236361	total: 60.5ms	remaining: 499ms
108:	learn: 1.8226051	total: 60.6ms	remaining: 495ms
109:	learn: 1.8215901	total: 60.7ms	remaining: 491ms
110:	learn: 1.8205908	total: 60.9ms	remaining: 488ms
111:	learn: 1.8196067	total: 61ms	remaining: 484ms
112:	learn: 1.8186376	total: 61.1ms	remaining: 480ms
113:	learn: 1.8176830	total: 61.3ms	remaining: 476ms
114:	learn: 1.8167426	total: 61.4ms	remaining: 473ms
115:	learn: 1.8158161	total: 61.6ms	remaining: 469ms
116:	learn: 1.8149032	total: 61.7ms	remaining: 466ms
117:	learn: 1.8140036	total: 61.8ms	remaining: 462ms
118:	learn: 1.8131169	total: 61.9ms	remaining: 459ms
119:	learn: 1.8122429	total: 62.1ms	remaining: 455ms
120:	learn: 1.8113813	total: 62.2ms	remaining: 452ms
121:	learn: 1.8105319	total: 62.4ms	remaining: 449ms
122:	learn: 1.8096943	total: 62.5ms	remaining: 446ms
123:	learn: 1.8088683	total: 62.6ms	remaining: 442ms
124:	learn: 1.8080538	total: 62.7ms	remaining: 439ms
125:	learn: 1.8072504	total: 62.9ms	remaining: 436ms
126:	learn: 1.8064579	total: 63ms	remaining: 433ms
127:	learn: 1.8056760	total: 63.2ms	remaining: 431ms
128:	learn: 1.8049047	total: 63.4ms	remaining: 428ms
129:	learn: 1.8041436	total: 63.6ms	remaining: 426ms
130:	learn: 1.8033926	total: 63.8ms	remaining: 423ms
131:	learn: 1.8026515	total: 63.9ms	remaining: 420ms
132:	learn: 1.8019200	total: 64.1ms	remaining: 418ms
133:	learn: 1.8011980	total: 64.2ms	remaining: 415ms
134:	learn: 1.8004853	total: 64.4ms	remaining: 413ms
135:	learn: 1.7997818	total: 64.6ms	remaining: 410ms
136:	learn: 1.7990872	total: 64.7ms	remaining: 408ms
137:	learn: 1.7984014	total: 64.9ms	remaining: 405ms
138:	learn: 1.7977242	total: 65ms	remaining: 403ms
139:	learn: 1.7970554	total: 65.2ms	remaining: 400ms
140:	learn: 1.7963950	total: 65.3ms	remaining: 398ms
141:	learn: 1.7957428	total: 65.5ms	remaining: 396ms
142:	learn: 1.7950986	total: 65.7ms	remaining: 394ms
143:	learn: 1.7944622	total: 65.8ms	remaining: 391ms
144:	learn: 1.7938336	total: 66ms	remaining: 389ms
145:	learn: 1.7932126	total: 66.1ms	remaining: 387ms
146:	learn: 1.7925990	total: 66.3ms	remaining: 385ms
147:	learn: 1.7919928	total: 66.4ms	remaining: 382ms
148:	learn: 1.7913938	total: 66.6ms	remaining: 380ms
149:	learn: 1.7908019	total: 66.7ms	remaining: 378ms
150:	learn: 1.7902169	total: 66.9ms	remaining: 376ms
151:	learn: 1.7896389	total: 67ms	remaining: 374ms
152:	learn: 1.7890675	total: 67.2ms	remaining: 372ms
153:	learn: 1.7885028	total: 67.3ms	remaining: 370ms
154:	learn: 1.7879446	total: 67.5ms	remaining: 368ms
155:	learn: 1.7873928	total: 67.6ms	remaining: 366ms
156:	learn: 1.7868473	total: 67.8ms	remaining: 364ms
157:	learn: 1.7863080	total: 68ms	remaining: 362ms
158:	learn: 1.7857749	total: 68.1ms	remaining: 360ms
159:	learn: 1.7852477	total: 68.3ms	remaining: 358ms
160:	learn: 1.7847264	total: 68.5ms	remaining: 357ms
161:	learn: 1.7842110	total: 68.6ms	remaining: 355ms
162:	learn: 1.7837013	total: 68.8ms	remaining: 353ms
163:	learn: 1.7831972	total: 68.9ms	remaining: 351ms
164:	learn: 1.7826987	total: 69.1ms	remaining: 350ms
165:	learn: 1.7822057	total: 69.3ms	remaining: 348ms
166:	learn: 1.7817180	total: 69.4ms	remaining: 346ms
167:	learn: 1.7812357	total: 69.6ms	remaining: 345ms
168:	learn: 1.7807585	total: 69.7ms	remaining: 343ms
169:	learn: 1.7802865	total: 69.9ms	remaining: 341ms
170:	learn: 1.7798196	total: 70ms	remaining: 340ms
171:	learn: 1.7793576	total: 70.2ms	remaining: 338ms
172:	learn: 1.7789006	total: 70.3ms	remaining: 336ms
173:	learn: 1.7784484	total: 70.5ms	remaining: 335ms
174:	learn: 1.7780010	total: 70.7ms	remaining: 333ms
175:	learn: 1.7775583	total: 70.8ms	remaining: 332ms
176:	learn: 1.7771202	total: 71ms	remaining: 330ms
177:	learn: 1.7766866	total: 71.1ms	remaining: 328ms
178:	learn: 1.7762576	total: 71.3ms	remaining: 327ms
179:	learn: 1.7758330	total: 71.4ms	remaining: 325ms
180:	learn: 1.7754128	total: 71.6ms	remaining: 324ms
181:	learn: 1.7749969	total: 71.7ms	remaining: 322ms
182:	learn: 1.7745852	total: 71.9ms	remaining: 321ms
183:	learn: 1.7741777	total: 72ms	remaining: 319ms
184:	learn: 1.7737743	total: 72.2ms	remaining: 318ms
185:	learn: 1.7733751	total: 72.3ms	remaining: 317ms
186:	learn: 1.7729798	total: 72.5ms	remaining: 315ms
187:	learn: 1.7725885	total: 72.6ms	remaining: 314ms
188:	learn: 1.7722010	total: 72.8ms	remaining: 312ms
189:	learn: 1.7718175	total: 72.9ms	remaining: 311ms
190:	learn: 1.7714377	total: 73.1ms	remaining: 310ms
191:	learn: 1.7710616	total: 73.2ms	remaining: 308ms
192:	learn: 1.7706893	total: 73.4ms	remaining: 307ms
193:	learn: 1.7703206	total: 73.5ms	remaining: 306ms
194:	learn: 1.7699555	total: 73.7ms	remaining: 304ms
195:	learn: 1.7695939	total: 73.8ms	remaining: 303ms
196:	learn: 1.7692359	total: 74ms	remaining: 302ms
197:	learn: 1.7688812	total: 74.2ms	remaining: 300ms
198:	learn: 1.7685300	total: 74.3ms	remaining: 299ms
199:	learn: 1.7681821	total: 74.5ms	remaining: 298ms
200:	learn: 1.7678376	total: 74.6ms	remaining: 297ms
201:	learn: 1.7674963	total: 74.8ms	remaining: 295ms
202:	learn: 1.7671583	total: 74.9ms	remaining: 294ms
203:	learn: 1.7668234	total: 75.1ms	remaining: 293ms
204:	learn: 1.7664917	total: 75.2ms	remaining: 292ms
205:	learn: 1.7661630	total: 75.4ms	remaining: 290ms
206:	learn: 1.7658375	total: 75.5ms	remaining: 289ms
207:	learn: 1.7655149	total: 75.7ms	remaining: 288ms
208:	learn: 1.7651953	total: 75.8ms	remaining: 287ms
209:	learn: 1.7648787	total: 76ms	remaining: 286ms
210:	learn: 1.7645650	total: 76.1ms	remaining: 285ms
211:	learn: 1.7642542	total: 76.3ms	remaining: 283ms
212:	learn: 1.7639461	total: 76.4ms	remaining: 282ms
213:	learn: 1.7636409	total: 76.6ms	remaining: 281ms
214:	learn: 1.7633385	total: 76.7ms	remaining: 280ms
215:	learn: 1.7630387	total: 76.9ms	remaining: 279ms
216:	learn: 1.7627417	total: 77ms	remaining: 278ms
217:	learn: 1.7624473	total: 77.2ms	remaining: 277ms
218:	learn: 1.7621555	total: 77.4ms	remaining: 276ms
219:	learn: 1.7618664	total: 77.5ms	remaining: 275ms
220:	learn: 1.7615798	total: 77.7ms	remaining: 274ms
221:	learn: 1.7612957	total: 77.8ms	remaining: 273ms
222:	learn: 1.7610141	total: 78ms	remaining: 272ms
223:	learn: 1.7607350	total: 78.1ms	remaining: 271ms
224:	learn: 1.7604583	total: 78.3ms	remaining: 270ms
225:	learn: 1.7601840	total: 78.4ms	remaining: 269ms
226:	learn: 1.7599121	total: 78.6ms	remaining: 268ms
227:	learn: 1.7596426	total: 78.7ms	remaining: 267ms
228:	learn: 1.7593753	total: 78.9ms	remaining: 266ms
229:	learn: 1.7591104	total: 79.1ms	remaining: 265ms
230:	learn: 1.7588477	total: 79.2ms	remaining: 264ms
231:	learn: 1.7585873	total: 79.4ms	remaining: 263ms
232:	learn: 1.7583290	total: 79.5ms	remaining: 262ms
233:	learn: 1.7580730	total: 79.7ms	remaining: 261ms
234:	learn: 1.7578191	total: 79.8ms	remaining: 260ms
235:	learn: 1.7575673	total: 80ms	remaining: 259ms
236:	learn: 1.7573177	total: 80.1ms	remaining: 258ms
237:	learn: 1.7570701	total: 80.3ms	remaining: 257ms
238:	learn: 1.7568246	total: 80.4ms	remaining: 256ms
239:	learn: 1.7565811	total: 80.6ms	remaining: 255ms
240:	learn: 1.7563396	total: 80.8ms	remaining: 254ms
241:	learn: 1.7561001	total: 80.9ms	remaining: 253ms
242:	learn: 1.7558626	total: 81.1ms	remaining: 253ms
243:	learn: 1.7556270	total: 81.2ms	remaining: 252ms
244:	learn: 1.7553934	total: 81.4ms	remaining: 251ms
245:	learn: 1.7551616	total: 81.5ms	remaining: 250ms
246:	learn: 1.7549317	total: 81.7ms	remaining: 249ms
247:	learn: 1.7547036	total: 81.8ms	remaining: 248ms
248:	learn: 1.7544774	total: 82ms	remaining: 247ms
249:	learn: 1.7542530	total: 82.1ms	remaining: 246ms
250:	learn: 1.7540304	total: 82.3ms	remaining: 246ms
251:	learn: 1.7538096	total: 82.4ms	remaining: 245ms
252:	learn: 1.7535905	total: 82.6ms	remaining: 244ms
253:	learn: 1.7533731	total: 82.7ms	remaining: 243ms
254:	learn: 1.7531574	total: 82.9ms	remaining: 242ms
255:	learn: 1.7529435	total: 83ms	remaining: 241ms
256:	learn: 1.7527312	total: 83.2ms	remaining: 241ms
257:	learn: 1.7525205	total: 83.7ms	remaining: 241ms
258:	learn: 1.7523115	total: 83.8ms	remaining: 240ms
259:	learn: 1.7521041	total: 84ms	remaining: 239ms
260:	learn: 1.7518983	total: 84.2ms	remaining: 238ms
261:	learn: 1.7516941	total: 84.3ms	remaining: 237ms
262:	learn: 1.7514915	total: 84.5ms	remaining: 237ms
263:	learn: 1.7512904	total: 84.6ms	remaining: 236ms
264:	learn: 1.7510908	total: 84.8ms	remaining: 235ms
265:	learn: 1.7508928	total: 85ms	remaining: 235ms
266:	learn: 1.7506962	total: 85.1ms	remaining: 234ms
267:	learn: 1.7505011	total: 85.3ms	remaining: 233ms
268:	learn: 1.7503075	total: 85.4ms	remaining: 232ms
269:	learn: 1.7501154	total: 85.6ms	remaining: 231ms
270:	learn: 1.7499246	total: 85.8ms	remaining: 231ms
271:	learn: 1.7497353	total: 85.9ms	remaining: 230ms
272:	learn: 1.7495474	total: 86.1ms	remaining: 229ms
273:	learn: 1.7493609	total: 86.2ms	remaining: 228ms
274:	learn: 1.7491758	total: 86.4ms	remaining: 228ms
275:	learn: 1.7489920	total: 86.6ms	remaining: 227ms
276:	learn: 1.7488096	total: 86.7ms	remaining: 226ms
277:	learn: 1.7486285	total: 86.9ms	remaining: 226ms
278:	learn: 1.7484487	total: 87ms	remaining: 225ms
279:	learn: 1.7482702	total: 87.2ms	remaining: 224ms
280:	learn: 1.7480930	total: 87.4ms	remaining: 224ms
281:	learn: 1.7479171	total: 87.5ms	remaining: 223ms
282:	learn: 1.7477424	total: 87.6ms	remaining: 222ms
283:	learn: 1.7475690	total: 87.8ms	remaining: 221ms
284:	learn: 1.7473969	total: 88ms	remaining: 221ms
285:	learn: 1.7472259	total: 88.1ms	remaining: 220ms
286:	learn: 1.7470562	total: 88.3ms	remaining: 219ms
287:	learn: 1.7468877	total: 88.4ms	remaining: 219ms
288:	learn: 1.7467203	total: 88.6ms	remaining: 218ms
289:	learn: 1.7465542	total: 88.7ms	remaining: 217ms
290:	learn: 1.7463892	total: 88.9ms	remaining: 217ms
291:	learn: 1.7462253	total: 89ms	remaining: 216ms
292:	learn: 1.7460626	total: 89.2ms	remaining: 215ms
293:	learn: 1.7459010	total: 89.3ms	remaining: 215ms
294:	learn: 1.7457406	total: 89.5ms	remaining: 214ms
295:	learn: 1.7455812	total: 89.6ms	remaining: 213ms
296:	learn: 1.7454230	total: 89.8ms	remaining: 213ms
297:	learn: 1.7452658	total: 89.9ms	remaining: 212ms
298:	learn: 1.7451097	total: 90.1ms	remaining: 211ms
299:	learn: 1.7449547	total: 90.2ms	remaining: 211ms
300:	learn: 1.7448007	total: 90.4ms	remaining: 210ms
301:	learn: 1.7446477	total: 90.5ms	remaining: 209ms
302:	learn: 1.7444958	total: 90.7ms	remaining: 209ms
303:	learn: 1.7443450	total: 90.8ms	remaining: 208ms
304:	learn: 1.7441951	total: 91ms	remaining: 207ms
305:	learn: 1.7440462	total: 91.1ms	remaining: 207ms
306:	learn: 1.7438983	total: 91.3ms	remaining: 206ms
307:	learn: 1.7437514	total: 91.5ms	remaining: 205ms
308:	learn: 1.7436055	total: 91.6ms	remaining: 205ms
309:	learn: 1.7434606	total: 91.7ms	remaining: 204ms
310:	learn: 1.7433166	total: 91.9ms	remaining: 204ms
311:	learn: 1.7431735	total: 92.1ms	remaining: 203ms
312:	learn: 1.7430314	total: 92.2ms	remaining: 202ms
313:	learn: 1.7428902	total: 92.4ms	remaining: 202ms
314:	learn: 1.7427499	total: 92.5ms	remaining: 201ms
315:	learn: 1.7426106	total: 92.7ms	remaining: 201ms
316:	learn: 1.7424721	total: 92.8ms	remaining: 200ms
317:	learn: 1.7423346	total: 93ms	remaining: 199ms
318:	learn: 1.7421979	total: 93.1ms	remaining: 199ms
319:	learn: 1.7420621	total: 93.3ms	remaining: 198ms
320:	learn: 1.7419272	total: 93.4ms	remaining: 198ms
321:	learn: 1.7417931	total: 93.6ms	remaining: 197ms
322:	learn: 1.7416599	total: 93.7ms	remaining: 196ms
323:	learn: 1.7415275	total: 93.9ms	remaining: 196ms
324:	learn: 1.7413960	total: 94ms	remaining: 195ms
325:	learn: 1.7412653	total: 94.2ms	remaining: 195ms
326:	learn: 1.7411354	total: 94.3ms	remaining: 194ms
327:	learn: 1.7410064	total: 94.5ms	remaining: 194ms
328:	learn: 1.7408781	total: 94.7ms	remaining: 193ms
329:	learn: 1.7407507	total: 94.8ms	remaining: 193ms
330:	learn: 1.7406240	total: 95ms	remaining: 192ms
331:	learn: 1.7404981	total: 95.1ms	remaining: 191ms
332:	learn: 1.7403730	total: 95.3ms	remaining: 191ms
333:	learn: 1.7402487	total: 95.4ms	remaining: 190ms
334:	learn: 1.7401251	total: 95.6ms	remaining: 190ms
335:	learn: 1.7400023	total: 95.7ms	remaining: 189ms
336:	learn: 1.7398803	total: 95.9ms	remaining: 189ms
337:	learn: 1.7397590	total: 96ms	remaining: 188ms
338:	learn: 1.7396384	total: 96.2ms	remaining: 188ms
339:	learn: 1.7395186	total: 96.4ms	remaining: 187ms
340:	learn: 1.7393994	total: 96.5ms	remaining: 186ms
341:	learn: 1.7392810	total: 96.6ms	remaining: 186ms
342:	learn: 1.7391634	total: 96.8ms	remaining: 185ms
343:	learn: 1.7390464	total: 97ms	remaining: 185ms
344:	learn: 1.7389301	total: 97.1ms	remaining: 184ms
345:	learn: 1.7388145	total: 97.3ms	remaining: 184ms
346:	learn: 1.7386996	total: 97.4ms	remaining: 183ms
347:	learn: 1.7385854	total: 97.6ms	remaining: 183ms
348:	learn: 1.7384719	total: 97.7ms	remaining: 182ms
349:	learn: 1.7383590	total: 97.9ms	remaining: 182ms
350:	learn: 1.7382468	total: 98ms	remaining: 181ms
351:	learn: 1.7381353	total: 98.2ms	remaining: 181ms
352:	learn: 1.7380244	total: 98.3ms	remaining: 180ms
353:	learn: 1.7379141	total: 98.5ms	remaining: 180ms
354:	learn: 1.7378045	total: 98.6ms	remaining: 179ms
355:	learn: 1.7376956	total: 98.8ms	remaining: 179ms
356:	learn: 1.7375872	total: 99ms	remaining: 178ms
357:	learn: 1.7374795	total: 99.1ms	remaining: 178ms
358:	learn: 1.7373724	total: 99.2ms	remaining: 177ms
359:	learn: 1.7372660	total: 99.4ms	remaining: 177ms
360:	learn: 1.7371601	total: 99.5ms	remaining: 176ms
361:	learn: 1.7370548	total: 99.7ms	remaining: 176ms
362:	learn: 1.7369502	total: 99.8ms	remaining: 175ms
363:	learn: 1.7368461	total: 100ms	remaining: 175ms
364:	learn: 1.7367427	total: 100ms	remaining: 174ms
365:	learn: 1.7366398	total: 100ms	remaining: 174ms
366:	learn: 1.7365375	total: 100ms	remaining: 173ms
367:	learn: 1.7364357	total: 101ms	remaining: 173ms
368:	learn: 1.7363346	total: 101ms	remaining: 172ms
369:	learn: 1.7362340	total: 101ms	remaining: 172ms
370:	learn: 1.7361340	total: 101ms	remaining: 171ms
371:	learn: 1.7360345	total: 101ms	remaining: 171ms
372:	learn: 1.7359356	total: 101ms	remaining: 170ms
373:	learn: 1.7358372	total: 102ms	remaining: 170ms
374:	learn: 1.7357394	total: 102ms	remaining: 169ms
375:	learn: 1.7356421	total: 102ms	remaining: 169ms
376:	learn: 1.7355453	total: 102ms	remaining: 169ms
377:	learn: 1.7354491	total: 102ms	remaining: 168ms
378:	learn: 1.7353534	total: 102ms	remaining: 168ms
379:	learn: 1.7352582	total: 102ms	remaining: 167ms

CatBoostClassifier()

In [34]:
y_pred4=q.predict(x_test)
y_pred4

array([[8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8],
       [8]])

In [78]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder
model5=XGBClassifier()
model5.fit(x_train, y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [79]:
y_pred5=model5.predict(x_test)
y_pred5

array([6, 4, 6, 4, 4, 6, 6, 4, 4])

In [80]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred5)*100

11.11111111111111

In [81]:
from sklearn.ensemble import GradientBoostingClassifier
model6=GradientBoostingClassifier()
model6.fit(x_train,y_train)

GradientBoostingClassifier()

In [82]:
y_pred6=model6.predict(x_test)
y_pred6

array([8, 8, 8, 8, 8, 8, 8, 8, 8])

In [83]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred6)*100

22.22222222222222